---

- name: Refresh clamav database
  ansible.builtin.command: freshclam

- name: Restart clamav daemon
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop: "{{ clamav_services }}"
