---

- name: Converge
  hosts: all
  become: "{{ molecule['converge']['become'] | default('yes') }}"
  vars:
  tasks:
    - name: Include role 'ansible-role-clamav'
      include_role:
        name: ansible-role-clamav
